package com.example.testapplication

import androidx.room.Entity
import androidx.room.PrimaryKey
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch

/**
 * GeofenceEntity defines a geofence by:
 * - latitude
 * - longitude
 * - radius (in meter)
 * - crossings
 * - id (autogenerated - for Db)
 */
@Entity(tableName = "Geofence")
data class GeofenceEntity(
    @PrimaryKey
    val id: String,

    val latitude: Double,
    val longitude: Double,
    val radius: Float,
    val crossCount: Int = 0
) {
    // insert this Entity into Db
    fun save(dao: GeofenceDao){
        CoroutineScope(Dispatchers.IO).launch {
            dao.insert(this@GeofenceEntity)
        }
    }

    // print geofence name and crossing
    fun toPrint():String{
        return ("$id   :   $crossCount")
    }
}